import { GAME_CONFIG } from "./config.js";
import { renderCity } from "./city-controller.js";

const icon = { music: "♫", sound: "♪", motion: "↝" };
export function controls(settings, compact = false) {
  return `<div class="toggles ${compact ? "toggles--compact" : ""}">
    ${["music","sound","reducedMotion"].map(key => `<button class="icon-button" data-setting="${key}" aria-pressed="${settings[key]}" aria-label="${key === "music" ? "Музыка" : key === "sound" ? "Звуки" : "Уменьшить движение"}: ${settings[key] ? "включено" : "выключено"}">${key === "reducedMotion" ? icon.motion : icon[key]}<small>${settings[key] ? "Вкл" : "Выкл"}</small></button>`).join("")}
  </div>`;
}
export function home(state, hasSave) {
  return `<main class="screen home-screen"><section class="hero-copy"><div class="eyebrow">ЧИТАТЕЛЬ-ДЕТЕКТИВ</div><h1>Ночная миссия:<br><span>зажги ABCity</span></h1><p class="story">В ABCity погас свет!<br>Найди пары больших и маленьких букв и верни городу сияние.</p><div class="actions"><button class="primary" data-action="${hasSave ? "continue" : "start"}">${hasSave ? "Продолжить миссию" : "Начать миссию"} <b>→</b></button><button class="secondary" data-action="how">Как играть</button>${hasSave ? `<button class="text-button" data-action="reset">Начать заново</button>` : ""}</div></section><section class="city-card" aria-label="Тёмный ABCity">${renderCity(hasSave ? state.illumination : 0, state.finalComplete)}</section>${controls(state.settings)}</main>`;
}
export function how(state) {
  return `<main class="screen center-screen"><section class="modal-card wide"><button class="close" data-action="home" aria-label="Закрыть">×</button><div class="eyebrow">ИНСТРУКЦИЯ ДЕТЕКТИВА</div><h2>Как зажечь ABCity</h2><div class="example"><span>A</span><b>→</b><span>a</span><em>Пара!</em></div><ol class="steps"><li><b>1</b>Посмотри на большую букву.</li><li><b>2</b>Найди такую же маленькую букву.</li><li><b>3</b>Нажми на правильную пару.</li><li><b>4</b>Верные пары превращаются в свет.</li><li><b>5</b>Пройди три уровня, чтобы осветить город.</li></ol><div class="level-chips"><span>Easy — 3 буквы</span><span>Medium — 5 букв</span><span>Hard — 8 букв</span></div><p class="note">На Easy у тебя 3 жизни. Неиспользованные жизни переходят дальше, а на новом уровне добавляются ещё 3. Ошибочная буква станет светлячком.</p><button class="primary" data-action="start">Всё понятно!</button></section>${controls(state.settings)}</main>`;
}
export function levelIntro(state) {
  const level = GAME_CONFIG.levels[state.currentLevel];
  const messages = { easy: "Зажги первые фонари", medium: "Освети окна и дорожки", hard: "Верни городу всё сияние" };
  return `<main class="screen center-screen"><section class="modal-card level-intro"><div class="level-orb">${level.movingLetterCount}</div><div class="eyebrow">УРОВЕНЬ ${GAME_CONFIG.levelOrder.indexOf(state.currentLevel) + 1} ИЗ 3</div><h2>${level.label}</h2><p>${messages[state.currentLevel]}</p><div class="intro-stats"><span>✦ ${level.movingLetterCount} движущихся букв</span><span>♥ ${state.lives} ${state.lives === 1 ? "жизнь" : "жизней"}</span></div><button class="primary" data-action="play-level">Начать уровень <b>→</b></button></section>${controls(state.settings)}</main>`;
}
export function game(state, paused = false) {
  const level = GAME_CONFIG.levels[state.currentLevel];
  return `<main class="screen game-screen"><header class="game-header"><button class="icon-button" data-action="home" aria-label="На главный экран">⌂</button><div class="level-title"><b>${level.label}</b><span>Уровень ${GAME_CONFIG.levelOrder.indexOf(state.currentLevel)+1} из 3</span></div><div class="progress" aria-label="Прогресс ${state.progress[state.currentLevel]} из ${level.requiredMatches}"><i style="width:${state.progress[state.currentLevel]/level.requiredMatches*100}%"></i></div><div class="lives" aria-label="Жизни: ${state.lives}">${Array.from({length: state.lives},()=>"♥").join("")}</div><button class="icon-button" data-action="pause" aria-label="Пауза">Ⅱ</button>${controls(state.settings, true)}</header><section class="play-layout"><aside class="target-panel"><span>НАЙДИ ПАРУ</span><div id="target" class="target-letter">${state.currentTask.target}</div><p>Выбери такую же<br>маленькую букву</p></aside><section id="letter-area" class="letter-area" aria-label="Варианты маленьких букв">${state.currentTask.choices.map(letter => `<button class="letter-bubble" data-letter="${letter}" aria-label="Буква ${letter}">${letter}</button>`).join("")}<div id="effect-layer"></div></section><aside class="mini-city">${renderCity(state.illumination, false)}</aside></section><div id="feedback" class="feedback" role="status"></div>${paused ? `<div class="overlay"><section class="modal-card"><div class="level-orb">Ⅱ</div><h2>Миссия на паузе</h2><p>Буквы подождут тебя.</p><button class="primary" data-action="resume">Продолжить</button><button class="secondary" data-action="home">На главный экран</button></section></div>` : ""}</main>`;
}
export function milestone(state, final = false, retry = false) {
  if (retry) return `<main class="screen center-screen"><section class="modal-card"><div class="level-orb firefly">✦</div><h2>Светлячки улетели</h2><p>Давай попробуем уровень ещё раз! Пройденные уровни сохранены.</p><button class="primary" data-action="retry">Повторить уровень</button><button class="secondary" data-action="home">На главный экран</button></section></main>`;
  if (final) return `<main class="screen final-screen"><section class="city-card final-city">${renderCity(1, true)}</section><section class="final-card"><div class="eyebrow">МИССИЯ ВЫПОЛНЕНА</div><h1>ABCity снова сияет!</h1><p>Все 26 букв благодарят читателя-детектива.</p><button class="primary" data-action="replay">Сыграть ещё раз</button><button class="secondary" data-action="home">На главный экран</button></section>${controls(state.settings)}</main>`;
  const next = GAME_CONFIG.levelOrder[GAME_CONFIG.levelOrder.indexOf(state.currentLevel)+1];
  return `<main class="screen center-screen"><section class="modal-card wide complete-card"><div class="city-preview">${renderCity(state.illumination)}</div><div><div class="eyebrow">УРОВЕНЬ ПРОЙДЕН</div><h2>Часть города зажглась!</h2><p>Сохранено жизней: <b class="gold">♥ ${state.lives}</b><br>На уровне ${GAME_CONFIG.levels[next].label} добавятся ещё 3.</p><button class="primary" data-action="next-level">Дальше: ${GAME_CONFIG.levels[next].label} <b>→</b></button></div></section></main>`;
}
